"""
User repository (database access layer).

What this file does:
- Encapsulates all user-related SQLAlchemy queries.

Why it is needed:
- Services should not execute raw DB queries directly.
- Repository abstraction improves testability and keeps responsibilities clean.
"""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import User


class UserRepository:
    """
    Repository for `User` data operations.

    Input:
    - `db`: SQLAlchemy session from dependency injection.
    """

    def __init__(self, db: Session) -> None:
        self.db = db

    def get_by_email(self, email: str) -> User | None:
        """
        Fetch a user by email.

        Input:
        - `email`: user's email address.

        Output:
        - `User` if found, else `None`.
        """

        stmt = select(User).where(User.email == email)
        return self.db.execute(stmt).scalar_one_or_none()

    def get_by_id(self, user_id: int) -> User | None:
        """
        Fetch a user by primary key.

        Input:
        - `user_id`: user table primary key.

        Output:
        - `User` if found, else `None`.
        """

        stmt = select(User).where(User.id == user_id)
        return self.db.execute(stmt).scalar_one_or_none()

    def create(self, *, email: str, password_hash: str) -> User:
        """
        Create and persist a user row.

        Input:
        - `email`: unique email for the new user.
        - `password_hash`: bcrypt hash generated by the service layer.

        Output:
        - Persisted `User` entity.
        """

        user = User(email=email, password_hash=password_hash)
        self.db.add(user)
        self.db.commit()
        self.db.refresh(user)
        return user

